#!/usr/bin/env bash

set -e

ns=$(yq '.metadata.namespace' $1)
name=$(yq '.metadata.name' $1)
nsYaml=""
if [ ! -z "$ns" ]; then
nsYaml="namespace: $ns"
fi

htUser=$(yq '.spec.username' $1)
htPass=$(yq '.spec.password' $1)
htData=$(htpasswd -nb $htUser $htPass)

cat <<EOF
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: $name
  $nsYaml
data:
  auth: $(echo -e $htData | base64)
EOF