#!/usr/bin/env bash

set -e

myip="$(curl --silent ifconfig.me)"

cat <<EOF
apiVersion: v1
kind: Service
metadata:
  name: $(yq r $1 metadata.name)
  annotations:
    external-dns.alpha.kubernetes.io/hostname: $(yq r $1 hostname)
spec:
  type: ExternalName
  externalName: ${myip}
EOF
