#!/usr/bin/env bash

set -e

res="$(cat $1)"
shift
argsOneLiner="$@"

function getProp() {
    yaml=$1
    shift
    echo "$yaml" | yq "$@" -
}

name=$(getProp "$res" '.metadata.name')
length=$(getProp "$res" '.variables | length')
# echo $length >&2
secret=$(cat <<EOF
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${name}
data: 
EOF
)

for (( i=0; i<$length; i++ ))
do
varName=$(getProp "$res" ".variables.[$i]")
secret+=$(cat <<EOF
  
  ${varName}: $(printf '%s' ${!varName} | base64)
EOF
)
done

cat <<EOF
$secret
EOF